Feature / Launch Cell View
devpass-tech/challenge-space-app-android pull request #2
Opened 2022-04-13 23:42 UTC by LucasOliveiraSimao

### Descrição e Solução
- Foi implementado a feature LaunchCellView.
- Foi criado a tela de next launches.
- Foi criado uma classe de modelo para os dados, implementado recyclerview, adapter.
- Os dados pra inflar a lista foram mocada
 
### Checklist:
- [X] Não adiciona código duplicado
- [X] Não contém código comentado
- [X] Não contém código WIP
- [ ] Teste Unitário Implementado
 
### Evidências:

![Screenshot_20220413-193925](https://user-images.githubusercontent.com/79026006/163287134-370675f4-6f89-4eb9-b56b-9c1ec6967a5e.jpg)

2022-04-14 14:05 UTC, cesar1287 requested changes

2022-04-14 14:05 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/res/layout/list_item.xml
> +            tools:ignore="ContentDescription"
Nunca é bom dar ignore nos warnings Lucas

2022-04-14 14:05 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/res/layout/list_item.xml
> +        app:cardCornerRadius="25dp"
Esse poderia ter sido adicionar no arquivo de dimens também, ou feito um tema somente para o CardView, para reuso

2022-04-14 14:05 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/java/com/devpass/spaceapp/launchCellView/LaunchAdapter.kt
> +    private val imageLaunch = itemView.findViewById<ImageView>(R.id.iv_logo)
Como você já adicionou o binding para o projeto, caberia usar aqui também, no RecyclerView

2022-04-14 14:05 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/java/com/devpass/spaceapp/launchCellView/LaunchAdapter.kt
> +    fun updateList(contents: List<LaunchModel>) {
Sugiro dar uma olhada no `ListAdapter` ele já faz isso automaticamente para nós - <https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter>

2022-04-14 23:08 UTC, LucasOliveiraSimao commented
As alterações sugeridas foram feitas

2022-04-14 23:32 UTC, cesar1287 requested changes

2022-04-14 23:32 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/res/layout/activity_launch_cell_view.xml
> +        android:layout_width="match_parent"
Deveria ser 0dp, por convenção

2022-04-14 23:32 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/java/com/devpass/spaceapp/launchCellView/LaunchAdapter.kt
> +    class LaunchViewHolder(binding: ListItemBinding) : RecyclerView.ViewHolder(binding.root) {
Usar o binding e excluir o `findViewById`

2022-04-14 23:32 UTC, cesar1287 commented on solutions/devsprint-cesar-rodrigues-1/app/src/main/java/com/devpass/spaceapp/launchCellView/LaunchAdapter.kt
> +    private companion object : DiffUtil.ItemCallback<LaunchModel>() {
Deveria estar na própria model(`LaunchModel`)

2022-04-15 13:36 UTC, cesar1287 approved these changes
Boa @LucasOliveiraSimao

2022-04-15 13:36 UTC, merged